# Generated by Django 5.0.2 on 2026-03-31 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='supplierbillline',
            name='line_kind',
            field=models.CharField(choices=[('SERVICE', 'Service Cost (COGS)'), ('OPEX', 'Operating Expense')], default='SERVICE', max_length=10),
        ),
        migrations.AddField(
            model_name='supplierbillline',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.expensecategory'),
        ),
    ]
