# Generated by Django 5.0.2 on 2026-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_payment_note_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='party_name',
            field=models.CharField(blank=True, help_text='Custom party name when party type is OTHER.', max_length=255),
        ),
    ]
