# Generated by Django 5.0.2 on 2026-03-29 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_supplier', models.BooleanField(default=False)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_core.passenger')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_core.supplier')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='catalog.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('choice', 'Choice'), ('bool', 'Boolean')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=1)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='catalog.servicetype')),
            ],
            options={
                'ordering': ['order', 'key'],
                'unique_together': {('service_type', 'key')},
            },
        ),
    ]
