# Generated by Django 5.0.2 on 2026-03-29 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', max_length=20)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('main_passport', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(choices=[('AIRLINE', 'Airline'), ('HOTEL', 'Hotel'), ('DMC', 'DMC'), ('VISA', 'Visa'), ('INSURANCE', 'Insurance'), ('TRANSFER', 'Transfer'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('terms', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/')),
                ('category', models.CharField(choices=[('PASSPORT', 'Passport'), ('PAYMENT_SLIP', 'Payment Slip'), ('INVOICE_SCAN', 'Invoice Scan'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('SALES', 'Sales'), ('ACCOUNTING', 'Accounting'), ('ADMIN', 'Admin')], default='SALES', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_ar', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=64)),
                ('nationality', models.CharField(blank=True, max_length=64)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='accounts_core.client')),
                ('passport_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_core.attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_no', models.CharField(max_length=32, unique=True)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='accounts_core.client')),
                ('passengers', models.ManyToManyField(blank=True, related_name='files', to='accounts_core.passenger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
