# Generated by Django 5.0.2 on 2026-03-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20)),
                ('prefix', models.CharField(default='', max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('doc_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14)),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'rate_date')},
            },
        ),
    ]
