# Generated by Django 5.0.2 on 2026-05-12 13:17

from django.db import migrations, models


def seed_usd(apps, schema_editor):
    Currency = apps.get_model("accounts_core", "Currency")
    Currency.objects.get_or_create(
        code="USD",
        defaults={"name": "US Dollar", "is_active": True, "sort_order": 0},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0003_userprofile_and_invoice_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.RunPython(seed_usd, migrations.RunPython.noop),
    ]
