# Generated by Django 5.0.2 on 2026-06-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0010_employee_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Corporate: primary contact name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='name_en',
            field=models.CharField(help_text='Full name (individual) or company name (corporate).', max_length=255),
        ),
    ]
