from django.core.management.base import BaseCommand

from catalog.models import Destination

DEFAULT_DESTINATIONS = [
    ("Dubai", "UAE", 1),
    ("Abu Dhabi", "UAE", 2),
    ("Sharjah", "UAE", 3),
    ("Istanbul", "Turkey", 4),
    ("Antalya", "Turkey", 5),
    ("Paris", "France", 6),
    ("London", "United Kingdom", 7),
    ("Riyadh", "Saudi Arabia", 8),
    ("Jeddah", "Saudi Arabia", 9),
    ("Mecca", "Saudi Arabia", 10),
    ("Medina", "Saudi Arabia", 11),
    ("Beirut", "Lebanon", 12),
    ("Cairo", "Egypt", 13),
    ("Alexandria", "Egypt", 14),
    ("Amman", "Jordan", 15),
    ("Doha", "Qatar", 16),
    ("Kuwait City", "Kuwait", 17),
    ("Manama", "Bahrain", 18),
    ("Muscat", "Oman", 19),
    ("Rome", "Italy", 20),
    ("Milan", "Italy", 21),
    ("Venice", "Italy", 22),
    ("Florence", "Italy", 23),
    ("Barcelona", "Spain", 24),
    ("Madrid", "Spain", 25),
    ("Athens", "Greece", 26),
    ("Santorini", "Greece", 27),
    ("Bangkok", "Thailand", 28),
    ("Phuket", "Thailand", 29),
    ("Singapore", "Singapore", 30),
    ("Kuala Lumpur", "Malaysia", 31),
    ("Bali", "Indonesia", 32),
    ("Jakarta", "Indonesia", 33),
    ("Tokyo", "Japan", 34),
    ("New York", "United States", 35),
    ("Los Angeles", "United States", 36),
    ("Miami", "United States", 37),
    ("Las Vegas", "United States", 38),
    ("Toronto", "Canada", 39),
    ("Vancouver", "Canada", 40),
    ("Sydney", "Australia", 41),
    ("Melbourne", "Australia", 42),
    ("Zurich", "Switzerland", 43),
    ("Geneva", "Switzerland", 44),
    ("Vienna", "Austria", 45),
    ("Prague", "Czech Republic", 46),
    ("Amsterdam", "Netherlands", 47),
    ("Brussels", "Belgium", 48),
    ("Berlin", "Germany", 49),
    ("Munich", "Germany", 50),
    ("Frankfurt", "Germany", 51),
    ("Lisbon", "Portugal", 52),
    ("Porto", "Portugal", 53),
    ("Dublin", "Ireland", 54),
    ("Edinburgh", "United Kingdom", 55),
    ("Manchester", "United Kingdom", 56),
    ("Moscow", "Russia", 57),
    ("Saint Petersburg", "Russia", 58),
    ("Baku", "Azerbaijan", 59),
    ("Tbilisi", "Georgia", 60),
    ("Yerevan", "Armenia", 61),
    ("Tehran", "Iran", 62),
    ("Islamabad", "Pakistan", 63),
    ("Karachi", "Pakistan", 64),
    ("Lahore", "Pakistan", 65),
    ("Delhi", "India", 66),
    ("Mumbai", "India", 67),
    ("Goa", "India", 68),
    ("Colombo", "Sri Lanka", 69),
    ("Male", "Maldives", 70),
    ("Kathmandu", "Nepal", 71),
    ("Dhaka", "Bangladesh", 72),
    ("Manila", "Philippines", 73),
    ("Seoul", "South Korea", 74),
    ("Beijing", "China", 75),
    ("Shanghai", "China", 76),
    ("Hong Kong", "China", 77),
    ("Macau", "China", 78),
    ("Taipei", "Taiwan", 79),
    ("Hanoi", "Vietnam", 80),
    ("Ho Chi Minh City", "Vietnam", 81),
    ("Phnom Penh", "Cambodia", 82),
    ("Vientiane", "Laos", 83),
    ("Nairobi", "Kenya", 84),
    ("Cape Town", "South Africa", 85),
    ("Marrakech", "Morocco", 86),
    ("Casablanca", "Morocco", 87),
    ("Tunis", "Tunisia", 88),
    ("Algiers", "Algeria", 89),
    ("Tripoli", "Libya", 90),
    ("Baghdad", "Iraq", 91),
    ("Erbil", "Iraq", 92),
    ("Damascus", "Syria", 93),
    ("Sanaa", "Yemen", 94),
    ("Addis Ababa", "Ethiopia", 95),
    ("Lagos", "Nigeria", 96),
    ("Accra", "Ghana", 97),
    ("Buenos Aires", "Argentina", 98),
    ("Rio de Janeiro", "Brazil", 99),
    ("Mexico City", "Mexico", 100),
]


class Command(BaseCommand):
    help = "Seed searchable destinations for invoice service lines."

    def handle(self, *args, **options):
        created = 0
        for name, country, order in DEFAULT_DESTINATIONS:
            _, was_created = Destination.objects.get_or_create(
                name=name,
                defaults={"country": country, "sort_order": order, "is_active": True},
            )
            if was_created:
                created += 1
        self.stdout.write(self.style.SUCCESS(f"Destinations ready ({created} new)."))
