# Generated by Django 5.0.2 on 2026-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
