# Generated by Django 5.0.2 on 2026-04-01 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0003_userprofile_and_invoice_lines'),
        ('catalog', '0001_initial'),
        ('sales', '0002_alter_salesinvoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='line_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='line_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='accounts_core.employee'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='catalog.servicetype'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='accounts_core.bookingfile'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='sales_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='accounts_core.employee'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='service_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='catalog.serviceinstance'),
        ),
    ]
