# Generated by Django 5.0.2 on 2026-05-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_core', '0003_userprofile_and_invoice_lines'),
        ('sales', '0003_userprofile_and_invoice_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='accounts_core.supplier'),
        ),
    ]
