# Generated by Django 5.0.2 on 2026-05-12 13:17

from decimal import Decimal

from django.db import migrations, models


def backfill_usd_amounts(apps, schema_editor):
    SalesInvoice = apps.get_model("sales", "SalesInvoice")
    SalesInvoiceLine = apps.get_model("sales", "SalesInvoiceLine")
    for inv in SalesInvoice.objects.all().iterator():
        inv.grand_total_usd = inv.grand_total
        inv.subtotal_usd = inv.subtotal
        inv.discount_total_usd = inv.discount_total
        inv.save(update_fields=["grand_total_usd", "subtotal_usd", "discount_total_usd"])
    for line in SalesInvoiceLine.objects.all().iterator():
        line.sell_price_usd = line.sell_price
        line.cost_price_usd = line.cost_price
        line.line_discount_usd = line.line_discount
        line.save(update_fields=["sell_price_usd", "cost_price_usd", "line_discount_usd"])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesinvoiceline_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='discount_total_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='exchange_rate_to_usd',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='How many units of invoice currency equal 1.00 USD (e.g. LBP per dollar). Not used when currency is USD.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='grand_total_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='cost_price_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='line_discount_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='sell_price_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.RunPython(backfill_usd_amounts, migrations.RunPython.noop),
    ]
