# Generated by Django 5.0.2 on 2026-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_system_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='is_full_package',
            field=models.BooleanField(default=False, help_text='Mark when this invoice is sold as a full travel package.'),
        ),
    ]
